title: ">_â˜ MSShells.net"
email: andresg@capazero.net
description: >- # this means to ignore newlines until "baseurl:"
  This site aims to keep track of the -current- Official Microsoft PowerShell modules to administer Microsoft 365 and Azure. Contributions are welcomed!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.msshells.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andresgorzelany
github_username:  get-itips

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
